
name: CI - Build and Lint

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Build client
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Check server syntax
        working-directory: ./server
        run: node --check server.js
